services:
  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: